json.id product.id
json.name product.name
json.price number_to_currency(product.price)
json.image product.image
json.description product.description
json.supplier product.supplier
json.created_at product.created_at
json.updated_at product.updated_at
json.is_discounted? product.is_discounted?
json.tax product.tax
json.total number_to_currency(product.total)
